using Xunit;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using SASD.Bewerbungsmanager.Domain.Entities;
using JobApplication = SASD.Bewerbungsmanager.Domain.Entities.Application;
using SASD.Bewerbungsmanager.Domain.Enums;
using SASD.Bewerbungsmanager.Infrastructure.Persistence;

namespace SASD.Bewerbungsmanager.Infrastructure.Tests;

public sealed class SqlitePersistenceTests
{
    [Fact]
    public async Task MigrationAndApplicationHistory_RoundTripThroughSqlite()
    {
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();
        var options = new DbContextOptionsBuilder<ApplicationTrackerDbContext>()
            .UseSqlite(connection)
            .Options;

        await using (var setup = new ApplicationTrackerDbContext(options))
        {
            await setup.Database.MigrateAsync();
        }

        var opportunity = new Opportunity
        {
            Id = Guid.NewGuid(),
            Title = "System Engineer Linux",
            DescriptionSnapshot = "Synthetische Stellenbeschreibung für einen Integrationstest.",
            Status = OpportunityStatus.Applied,
            FoundAtUtc = DateTimeOffset.UtcNow,
            CreatedAtUtc = DateTimeOffset.UtcNow,
            UpdatedAtUtc = DateTimeOffset.UtcNow,
        };
        var application = new JobApplication
        {
            Id = Guid.NewGuid(),
            OpportunityId = opportunity.Id,
            StartedAtUtc = DateTimeOffset.UtcNow,
            Channel = ApplicationChannel.Portal,
            CreatedAtUtc = DateTimeOffset.UtcNow,
            UpdatedAtUtc = DateTimeOffset.UtcNow,
        };
        application.InitializeStage(ApplicationStage.Submitted, DateTimeOffset.UtcNow, "Testversand");

        await using (var write = new ApplicationTrackerDbContext(options))
        {
            write.Opportunities.Add(opportunity);
            write.Applications.Add(application);
            await write.SaveChangesAsync();
        }

        await using (var update = new ApplicationTrackerDbContext(options))
        {
            var tracked = await update.Applications
                .Include("_statusHistory")
                .SingleAsync();

            // This is the regression path that previously failed: the application already exists
            // and receives a new dependent history entity whose Guid was generated by the domain.
            tracked.ChangeStage(ApplicationStage.Interview, DateTimeOffset.UtcNow, "Testinterview");
            await update.SaveChangesAsync();
        }

        await using var read = new ApplicationTrackerDbContext(options);
        var loaded = await read.Applications.Include("_statusHistory").SingleAsync();

        Assert.Equal(ApplicationStage.Interview, loaded.Stage);
        Assert.Equal(2, loaded.StatusHistory.Count);
        Assert.Contains(loaded.StatusHistory, item => item.Note == "Testversand");
        Assert.Contains(loaded.StatusHistory, item => item.Note == "Testinterview");
    }

    [Fact]
    public async Task ListMethods_OrderDateTimeOffsetValuesInMemoryForSqlite()
    {
        await using var connection = new SqliteConnection("Data Source=:memory:");
        await connection.OpenAsync();
        var options = new DbContextOptionsBuilder<ApplicationTrackerDbContext>()
            .UseSqlite(connection)
            .Options;

        await using (var setup = new ApplicationTrackerDbContext(options))
        {
            await setup.Database.MigrateAsync();
        }

        var older = new DateTimeOffset(2026, 8, 25, 10, 0, 0, TimeSpan.Zero);
        var newer = new DateTimeOffset(2026, 8, 26, 10, 0, 0, TimeSpan.Zero);

        var olderOpportunity = new Opportunity
        {
            Id = Guid.NewGuid(),
            Title = "Older opportunity",
            DescriptionSnapshot = "Synthetic older opportunity.",
            Status = OpportunityStatus.Identified,
            FoundAtUtc = older,
            CreatedAtUtc = older,
            UpdatedAtUtc = older,
        };
        var newerOpportunity = new Opportunity
        {
            Id = Guid.NewGuid(),
            Title = "Newer opportunity",
            DescriptionSnapshot = "Synthetic newer opportunity.",
            Status = OpportunityStatus.Identified,
            FoundAtUtc = newer,
            CreatedAtUtc = newer,
            UpdatedAtUtc = newer,
        };

        var olderApplication = new JobApplication
        {
            Id = Guid.NewGuid(),
            OpportunityId = olderOpportunity.Id,
            StartedAtUtc = older,
            Channel = ApplicationChannel.Email,
            CreatedAtUtc = older,
            UpdatedAtUtc = older,
        };
        olderApplication.InitializeStage(ApplicationStage.Draft, older);

        var newerApplication = new JobApplication
        {
            Id = Guid.NewGuid(),
            OpportunityId = newerOpportunity.Id,
            StartedAtUtc = newer,
            Channel = ApplicationChannel.Email,
            CreatedAtUtc = newer,
            UpdatedAtUtc = newer,
        };
        newerApplication.InitializeStage(ApplicationStage.Draft, newer);

        var olderSource = new SourceLink
        {
            Id = Guid.NewGuid(),
            OpportunityId = newerOpportunity.Id,
            Source = "Example Source",
            Url = "https://example.invalid/older",
            CapturedAtUtc = older,
        };
        var newerSource = new SourceLink
        {
            Id = Guid.NewGuid(),
            OpportunityId = newerOpportunity.Id,
            Source = "Example Source",
            Url = "https://example.invalid/newer",
            CapturedAtUtc = newer,
        };

        await using (var write = new ApplicationTrackerDbContext(options))
        {
            write.Opportunities.AddRange(olderOpportunity, newerOpportunity);
            write.Applications.AddRange(olderApplication, newerApplication);
            write.SourceLinks.AddRange(olderSource, newerSource);
            await write.SaveChangesAsync();
        }

        var store = new TrackerDataStore(new TestDbContextFactory(options));
        var opportunities = await store.ListOpportunitiesAsync();
        var applications = await store.ListApplicationsAsync();
        var sources = await store.ListSourceLinksAsync(newerOpportunity.Id);

        Assert.Equal(
            new[] { newerOpportunity.Id, olderOpportunity.Id },
            opportunities.Select(item => item.Id));
        Assert.Equal(
            new[] { newerApplication.Id, olderApplication.Id },
            applications.Select(item => item.Id));
        Assert.Equal(
            new[] { newerSource.Id, olderSource.Id },
            sources.Select(item => item.Id));
    }

    private sealed class TestDbContextFactory(DbContextOptions<ApplicationTrackerDbContext> options)
        : IDbContextFactory<ApplicationTrackerDbContext>
    {
        public ApplicationTrackerDbContext CreateDbContext() => new(options);

        public Task<ApplicationTrackerDbContext> CreateDbContextAsync(CancellationToken cancellationToken = default)
            => Task.FromResult(CreateDbContext());
    }
}
