<Project>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <Deterministic>true</Deterministic>
    <DebugType>portable</DebugType>
    <RepositoryUrl>https://github.com/Robin-Goerlach/SASD-Bewerbungsmanager</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Authors>SASD</Authors>
    <Company>SASD</Company>
    <Product>SASD Bewerbungsmanager</Product>
    <VersionPrefix>0.0.1</VersionPrefix>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <PropertyGroup Condition="'$(CI)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>
</Project>
