<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>SASD.Bewerbungsmanager.WinForms</RootNamespace>
    <AssemblyName>SASD.Bewerbungsmanager</AssemblyName>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationDefaultFont>Segoe UI, 9pt</ApplicationDefaultFont>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SASD.Bewerbungsmanager.Application\SASD.Bewerbungsmanager.Application.csproj" />
    <ProjectReference Include="..\SASD.Bewerbungsmanager.Infrastructure\SASD.Bewerbungsmanager.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" />
  </ItemGroup>
</Project>
